### ISSUE TITLE
Improve test workflow

### ISSUE THREAD

**Issue by airibarne** [dribia/driconfig#159]
1. Create a `lint.sh` workflow that runs the lint script, removing the run from the `test.yml` workflow. No need to run the lint on different Python versions, just use 3.11.
2. Add the corresponding badge to the `README.md`.
3. Modify the poetry install command on both lint and test workflows to install only the needed dependency groups. It might be necessary to add some `ci` group with common dependencies.
4. Drop Python 3.8 support from the test matrix (not from `pyproject.toml`) and add 3.11 and 3.12.

**Comment by mauro-dribia** [comment]
do we want actions running on all pushes? @airibarne

**Comment by airibarne** [comment]
@mauro-dribia ahora lo veo, not really, solamente en PR
